
on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/MrGorbunov/TestRepo.wiki.git"
          source_branch: "master"
          destination_repo: "https://github.com/MrGorbunov/TestRepo2.wiki.git"
          destination_branch: "master"
